version: '2.4'
services:
  mpd:
    image: tobi312/rpi-mpd:alpine
    container_name: mpd
    restart: unless-stopped
    ports:
      - 6600:6600  # MPD Client
      - 8000:8000  # Stream
    volumes:
      - ./run/music:/var/lib/mpd/music:rw
      - ./run/playlists:/var/lib/mpd/playlists:rw
      - ./run/data:/var/lib/mpd/data:rw
      #- ./mpd.conf:/etc/mpd.conf:rw
    devices:
      - "/dev/snd:/dev/snd"
