// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alarm_queries.sql

package db

import (
	"context"
	"database/sql"
)

const createAlarm = `-- name: CreateAlarm :exec
INSERT INTO alarms (
    id, label, time, enabled, warmup_duration, led_target, music_playlist_id, music_file_id
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateAlarmParams struct {
	ID              string
	Label           string
	Time            string
	Enabled         bool
	WarmupDuration  sql.NullInt64
	LedTarget       sql.NullString
	MusicPlaylistID sql.NullString
	MusicFileID     sql.NullString
}

func (q *Queries) CreateAlarm(ctx context.Context, arg CreateAlarmParams) error {
	_, err := q.db.ExecContext(ctx, createAlarm,
		arg.ID,
		arg.Label,
		arg.Time,
		arg.Enabled,
		arg.WarmupDuration,
		arg.LedTarget,
		arg.MusicPlaylistID,
		arg.MusicFileID,
	)
	return err
}

const deleteAlarm = `-- name: DeleteAlarm :exec
DELETE FROM alarms WHERE id = ?
`

func (q *Queries) DeleteAlarm(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAlarm, id)
	return err
}

const getAlarm = `-- name: GetAlarm :one
SELECT id, label, time, enabled, warmup_duration, led_target, music_playlist_id, music_file_id, created_at, updated_at FROM alarms WHERE id = ?
`

func (q *Queries) GetAlarm(ctx context.Context, id string) (Alarm, error) {
	row := q.db.QueryRowContext(ctx, getAlarm, id)
	var i Alarm
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Time,
		&i.Enabled,
		&i.WarmupDuration,
		&i.LedTarget,
		&i.MusicPlaylistID,
		&i.MusicFileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlarms = `-- name: ListAlarms :many
SELECT id, label, time, enabled, warmup_duration, led_target, music_playlist_id, music_file_id, created_at, updated_at FROM alarms ORDER BY time
`

func (q *Queries) ListAlarms(ctx context.Context) ([]Alarm, error) {
	rows, err := q.db.QueryContext(ctx, listAlarms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alarm
	for rows.Next() {
		var i Alarm
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Time,
			&i.Enabled,
			&i.WarmupDuration,
			&i.LedTarget,
			&i.MusicPlaylistID,
			&i.MusicFileID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleAlarm = `-- name: ToggleAlarm :exec
UPDATE alarms SET enabled = ? WHERE id = ?
`

type ToggleAlarmParams struct {
	Enabled bool
	ID      string
}

func (q *Queries) ToggleAlarm(ctx context.Context, arg ToggleAlarmParams) error {
	_, err := q.db.ExecContext(ctx, toggleAlarm, arg.Enabled, arg.ID)
	return err
}

const updateAlarm = `-- name: UpdateAlarm :exec
UPDATE alarms
SET label = ?, time = ?, enabled = ?, warmup_duration = ?, led_target = ?, music_playlist_id = ?, music_file_id = ?
WHERE id = ?
`

type UpdateAlarmParams struct {
	Label           string
	Time            string
	Enabled         bool
	WarmupDuration  sql.NullInt64
	LedTarget       sql.NullString
	MusicPlaylistID sql.NullString
	MusicFileID     sql.NullString
	ID              string
}

func (q *Queries) UpdateAlarm(ctx context.Context, arg UpdateAlarmParams) error {
	_, err := q.db.ExecContext(ctx, updateAlarm,
		arg.Label,
		arg.Time,
		arg.Enabled,
		arg.WarmupDuration,
		arg.LedTarget,
		arg.MusicPlaylistID,
		arg.MusicFileID,
		arg.ID,
	)
	return err
}
