// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_queries.sql

package db

import (
	"context"
	"database/sql"
)

const createMediaFile = `-- name: CreateMediaFile :exec
INSERT INTO media_files (id, title, artist, size_bytes, length_hms, mime_type, type)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateMediaFileParams struct {
	ID        string
	Title     string
	Artist    sql.NullString
	SizeBytes int64
	LengthHms string
	MimeType  string
	Type      int64
}

func (q *Queries) CreateMediaFile(ctx context.Context, arg CreateMediaFileParams) error {
	_, err := q.db.ExecContext(ctx, createMediaFile,
		arg.ID,
		arg.Title,
		arg.Artist,
		arg.SizeBytes,
		arg.LengthHms,
		arg.MimeType,
		arg.Type,
	)
	return err
}

const deleteMediaFile = `-- name: DeleteMediaFile :exec
DELETE FROM media_files WHERE id = ?
`

func (q *Queries) DeleteMediaFile(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMediaFile, id)
	return err
}

const listMediaFiles = `-- name: ListMediaFiles :many
SELECT id, title, artist, size_bytes, length_hms, mime_type, type, uploaded_at FROM media_files ORDER BY uploaded_at DESC LIMIT ? OFFSET ?
`

type ListMediaFilesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListMediaFiles(ctx context.Context, arg ListMediaFilesParams) ([]MediaFile, error) {
	rows, err := q.db.QueryContext(ctx, listMediaFiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaFile
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.SizeBytes,
			&i.LengthHms,
			&i.MimeType,
			&i.Type,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMediaFiles = `-- name: SearchMediaFiles :many
SELECT id, title, artist, size_bytes, length_hms, mime_type, type, uploaded_at FROM media_files
WHERE title LIKE '%' || ? || '%' OR artist LIKE '%' || ? || '%'
ORDER BY uploaded_at DESC LIMIT ? OFFSET ?
`

type SearchMediaFilesParams struct {
	Column1 sql.NullString
	Column2 sql.NullString
	Limit   int64
	Offset  int64
}

func (q *Queries) SearchMediaFiles(ctx context.Context, arg SearchMediaFilesParams) ([]MediaFile, error) {
	rows, err := q.db.QueryContext(ctx, searchMediaFiles,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaFile
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.SizeBytes,
			&i.LengthHms,
			&i.MimeType,
			&i.Type,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaFileMeta = `-- name: UpdateMediaFileMeta :exec
UPDATE media_files
SET title = COALESCE(?, title),
    artist = COALESCE(?, artist)
WHERE id = ?
`

type UpdateMediaFileMetaParams struct {
	Title  string
	Artist sql.NullString
	ID     string
}

func (q *Queries) UpdateMediaFileMeta(ctx context.Context, arg UpdateMediaFileMetaParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaFileMeta, arg.Title, arg.Artist, arg.ID)
	return err
}
