// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playlist_queries.sql

package db

import (
	"context"
)

const addPlaylistFile = `-- name: AddPlaylistFile :exec
INSERT INTO playlist_files (playlist_id, file_id, position)
VALUES (?, ?, ?)
`

type AddPlaylistFileParams struct {
	PlaylistID string
	FileID     string
	Position   int64
}

func (q *Queries) AddPlaylistFile(ctx context.Context, arg AddPlaylistFileParams) error {
	_, err := q.db.ExecContext(ctx, addPlaylistFile, arg.PlaylistID, arg.FileID, arg.Position)
	return err
}

const deletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM playlists WHERE id = ?
`

func (q *Queries) DeletePlaylist(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePlaylist, id)
	return err
}

const getPlaylist = `-- name: GetPlaylist :one
SELECT id, name, created_at, updated_at FROM playlists WHERE id = ?
`

func (q *Queries) GetPlaylist(ctx context.Context, id string) (Playlist, error) {
	row := q.db.QueryRowContext(ctx, getPlaylist, id)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaylistFiles = `-- name: GetPlaylistFiles :many
SELECT f.id, f.title, f.artist, f.size_bytes, f.length_hms, f.mime_type, f.type, f.uploaded_at FROM media_files f
JOIN playlist_files pf ON f.id = pf.file_id
WHERE pf.playlist_id = ?
ORDER BY pf.position
`

func (q *Queries) GetPlaylistFiles(ctx context.Context, playlistID string) ([]MediaFile, error) {
	rows, err := q.db.QueryContext(ctx, getPlaylistFiles, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaFile
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.SizeBytes,
			&i.LengthHms,
			&i.MimeType,
			&i.Type,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylists = `-- name: ListPlaylists :many
SELECT id, name, created_at, updated_at FROM playlists ORDER BY name
`

func (q *Queries) ListPlaylists(ctx context.Context) ([]Playlist, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playlist
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderPlaylistFiles = `-- name: ReorderPlaylistFiles :exec
UPDATE playlist_files SET position = ? WHERE playlist_id = ? AND file_id = ?
`

type ReorderPlaylistFilesParams struct {
	Position   int64
	PlaylistID string
	FileID     string
}

func (q *Queries) ReorderPlaylistFiles(ctx context.Context, arg ReorderPlaylistFilesParams) error {
	_, err := q.db.ExecContext(ctx, reorderPlaylistFiles, arg.Position, arg.PlaylistID, arg.FileID)
	return err
}

const updatePlaylist = `-- name: UpdatePlaylist :exec
UPDATE playlists SET name = ? WHERE id = ?
`

type UpdatePlaylistParams struct {
	Name string
	ID   string
}

func (q *Queries) UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) error {
	_, err := q.db.ExecContext(ctx, updatePlaylist, arg.Name, arg.ID)
	return err
}
