// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sleepscape_queries.sql

package db

import (
	"context"
	"database/sql"
)

const createSleepscape = `-- name: CreateSleepscape :exec
INSERT INTO sleepscapes
(id, name, source_type, source_id, source_name, led_expression, author, description, tags, verified)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSleepscapeParams struct {
	ID            string
	Name          string
	SourceType    int64
	SourceID      string
	SourceName    sql.NullString
	LedExpression sql.NullString
	Author        sql.NullString
	Description   sql.NullString
	Tags          sql.NullString
	Verified      sql.NullBool
}

func (q *Queries) CreateSleepscape(ctx context.Context, arg CreateSleepscapeParams) error {
	_, err := q.db.ExecContext(ctx, createSleepscape,
		arg.ID,
		arg.Name,
		arg.SourceType,
		arg.SourceID,
		arg.SourceName,
		arg.LedExpression,
		arg.Author,
		arg.Description,
		arg.Tags,
		arg.Verified,
	)
	return err
}

const deleteSleepscape = `-- name: DeleteSleepscape :exec
DELETE FROM sleepscapes WHERE id = ?
`

func (q *Queries) DeleteSleepscape(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSleepscape, id)
	return err
}

const getSleepscape = `-- name: GetSleepscape :one
SELECT id, name, source_type, source_id, source_name, led_expression, author, description, tags, verified, created_at, updated_at FROM sleepscapes WHERE id = ?
`

func (q *Queries) GetSleepscape(ctx context.Context, id string) (Sleepscape, error) {
	row := q.db.QueryRowContext(ctx, getSleepscape, id)
	var i Sleepscape
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SourceType,
		&i.SourceID,
		&i.SourceName,
		&i.LedExpression,
		&i.Author,
		&i.Description,
		&i.Tags,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSleepscapes = `-- name: ListSleepscapes :many
SELECT id, name, source_type, source_id, source_name, led_expression, author, description, tags, verified, created_at, updated_at FROM sleepscapes ORDER BY name LIMIT ? OFFSET ?
`

type ListSleepscapesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListSleepscapes(ctx context.Context, arg ListSleepscapesParams) ([]Sleepscape, error) {
	rows, err := q.db.QueryContext(ctx, listSleepscapes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sleepscape
	for rows.Next() {
		var i Sleepscape
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SourceType,
			&i.SourceID,
			&i.SourceName,
			&i.LedExpression,
			&i.Author,
			&i.Description,
			&i.Tags,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSleepscape = `-- name: UpdateSleepscape :exec
UPDATE sleepscapes
SET name = ?, source_type = ?, source_id = ?, source_name = ?, led_expression = ?,
    author = ?, description = ?, tags = ?, verified = ?
WHERE id = ?
`

type UpdateSleepscapeParams struct {
	Name          string
	SourceType    int64
	SourceID      string
	SourceName    sql.NullString
	LedExpression sql.NullString
	Author        sql.NullString
	Description   sql.NullString
	Tags          sql.NullString
	Verified      sql.NullBool
	ID            string
}

func (q *Queries) UpdateSleepscape(ctx context.Context, arg UpdateSleepscapeParams) error {
	_, err := q.db.ExecContext(ctx, updateSleepscape,
		arg.Name,
		arg.SourceType,
		arg.SourceID,
		arg.SourceName,
		arg.LedExpression,
		arg.Author,
		arg.Description,
		arg.Tags,
		arg.Verified,
		arg.ID,
	)
	return err
}
